<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 02: Evaluate the Diabetes Dataset

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: Import the dataset

In [128]:
#Import the required libraries
import numpy as np
import pandas as pd

In [129]:
#Import the diabetes dataset
dataset = pd.read_csv('/Users/rajeshsahu/Desktop/Lesson 8-2/pima-indians-diabetes.data',header=None)

#### 2: Analyze the dataset

In [130]:
#View the first five observations of the dataset
print(dataset.head(5))

   0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1


#### 3: Find the features of the dataset

In [131]:
#Use the .NAMES file to view and set the features of the dataset
names = np.array(['Number of times pregnant','Plasma glucose concentration a 2 hours in an oral glucose tolerance test','Diastolic blood pressure (mm Hg)','Triceps skin fold','thickness (mm)','2-Hour serum insulin (mu U/ml)','Body mass index (weight in kg/(height in m)^2)','Diabetes pedigree function,Age (years)','Class variable (0 or 1)'])


In [132]:
#Use the feature names set earlier and fix it as the column headers of the dataset
dataset.columns = names

In [133]:
#Verify if the dataset is updated with the new headers
dataset

Number of times pregnant  \
0                           6   
1                           1   
2                           8   
3                           1   
4                           0   
..                        ...   
763                        10   
764                         2   
765                         5   
766                         1   
767                         1   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                  148                          
1                                                   85                          
2                                                  183                          
3                                                   89                          
4                                                  137                          
..                                                 ...                          
763                                                101                          
764                                                122                          
765                                                121                          
766                                                126                          
767                                                 93                          

     Diastolic blood pressure (mm Hg)  Triceps skin fold  thickness (mm)  \
0                                  72                 35               0   
1                                  66                 29               0   
2                                  64                  0               0   
3                                  66                 23              94   
4                                  40                 35             168   
..                                ...                ...             ...   
763                                76                 48             180   
764                                70                 27               0   
765                                72                 23             112   
766                                60                  0               0   
767                                70                 31               0   

     2-Hour serum insulin (mu U/ml)  \
0                              33.6   
1                              26.6   
2                              23.3   
3                              28.1   
4                              43.1   
..                              ...   
763                            32.9   
764                            36.8   
765                            26.2   
766                            30.1   
767                            30.4   

     Body mass index (weight in kg/(height in m)^2)  \
0                                             0.627   
1                                             0.351   
2                                             0.672   
3                                             0.167   
4                                             2.288   
..                                              ...   
763                                           0.171   
764                                           0.340   
765                                           0.245   
766                                           0.349   
767                                           0.315   

     Diabetes pedigree function,Age (years)  Class variable (0 or 1)  
0                                        50                        1  
1                                        31                        0  
2                                        32                        1  
3                                        21                        0  
4                                        33                        1  
..                                      ...                      ...  
763                                      63                        0  
764                     

In [134]:
#View the number of observations and features of the dataset
print(len(dataset.values),len(dataset.columns))

768 9


#### 4: Find the response  of the dataset

In [135]:
#Select features from the dataset to create the model
X_feature = dataset.drop('Class variable (0 or 1)',axis='columns')
X_feature = X_feature[['Plasma glucose concentration a 2 hours in an oral glucose tolerance test','2-Hour serum insulin (mu U/ml)','Body mass index (weight in kg/(height in m)^2)']]

In [136]:
#Create the feature object
X_feature = X_feature.values

In [137]:
#Create the reponse object
Y_target = dataset['Class variable (0 or 1)']

In [138]:
#View the shape of the feature object
print(X_feature)

[[148.     33.6     0.627]
 [ 85.     26.6     0.351]
 [183.     23.3     0.672]
 ...
 [121.     26.2     0.245]
 [126.     30.1     0.349]
 [ 93.     30.4     0.315]]


In [139]:
#View the shape of the target object
print(Y_target)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Class variable (0 or 1), Length: 768, dtype: int64


#### 5: Use training and testing datasets to train the model

In [140]:
#Split the dataset to test and train the model
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_feature,Y_target,test_size=0.25)

#### 6: Create a model  to predict the diabetes outcome

In [141]:
# Create a logistic regression model using the training set
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()
logReg.fit(X_train,Y_train)

LogisticRegression()

In [142]:
#Make predictions using the testing set
Y_predict = logReg.predict(X_test)

#### 7: Check the accuracy of the model

In [145]:
#Evaluate the accuracy of your model
from sklearn.metrics import accuracy_score,average_precision_score,confusion_matrix,f1_score,recall_score
print("accuracy_score",accuracy_score(Y_test,Y_predict))
print("average_precision_score",average_precision_score(Y_test,Y_predict))
print("confusion_matrix\n",confusion_matrix(Y_test,Y_predict))
print("\nrecall_score",recall_score(Y_test,Y_predict))
print("\nf1_score",f1_score(Y_test,Y_predict))

accuracy_score 0.765625
average_precision_score 0.5569159267480577
confusion_matrix
 [[109  15]
 [ 30  38]]

recall_score 0.5588235294117647

f1_score 0.6280991735537189


In [144]:
#Print the first 30 actual and predicted response
for i in range(0,30):
    print(list(Y_test)[i],list(Y_predict)[i])

0 1
1 1
0 0
0 0
0 0
0 0
1 1
0 0
0 0
0 0
0 1
1 0
0 0
0 0
0 0
1 1
0 1
0 0
1 1
0 0
0 0
0 0
1 1
0 0
0 0
0 0
1 0
0 0
1 0
1 0
