In [230]:
import pandas as pd
import numpy as np
import string
from nltk.corpus import stopwords

In [231]:
#Get the spam data collection 
#Get the spam data collection 
dataset = pd.read_csv('/Users/rajeshsahu/Desktop/Data Science Learning/Lesson 9 -1/SpamCollection/SpamCollection',sep='\t',header=None)

In [232]:
dataset.columns = ['res','feat']

In [233]:
(dataset)

res                                               feat
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [234]:
#view response 
dataset.res

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: res, Length: 5572, dtype: object

In [235]:
#Verify length of the messages and also add it as a new column 
dataset['length'] = dataset.feat.apply(len)

In [236]:
dataset

res                                               feat  length
0      ham  Go until jurong point, crazy.. Available only ...     111
1      ham                      Ok lar... Joking wif u oni...      29
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3      ham  U dun say so early hor... U c already then say...      49
4      ham  Nah I don't think he goes to usf, he lives aro...      61
...    ...                                                ...     ...
5567  spam  This is the 2nd time we have tried 2 contact u...     160
5568   ham               Will ü b going to esplanade fr home?      36
5569   ham  Pity, * was in mood for that. So...any other s...      57
5570   ham  The guy did some bitching but I acted like i'd...     125
5571   ham                         Rofl. Its true to its name      26

[5572 rows x 3 columns]

In [237]:
#define a function to get rid of stopwords present in the messages
def remove_stopwords(msg):
    no_punctuation = [char for char in msg if char not in string.punctuation]
    no_punctuation_msg = ''.join(no_punctuation)
    clean_sentence = [word for word in no_punctuation_msg.split() if word.lower() not in stopwords.words('english')]
    clean_sentence = ' '.join(clean_sentence)
    return clean_sentence

dataset.feat = dataset.feat.apply(remove_stopwords)

In [238]:
dataset['New_length'] = dataset.feat.apply(len)
dataset

res                                               feat  length  \
0      ham  Go jurong point crazy Available bugis n great ...     111   
1      ham                            Ok lar Joking wif u oni      29   
2     spam  Free entry 2 wkly comp win FA Cup final tkts 2...     155   
3      ham                U dun say early hor U c already say      49   
4      ham        Nah dont think goes usf lives around though      61   
...    ...                                                ...     ...   
5567  spam  2nd time tried 2 contact u U £750 Pound prize ...     160   
5568   ham                        ü b going esplanade fr home      36   
5569   ham                        Pity mood Soany suggestions      57   
5570   ham  guy bitching acted like id interested buying s...     125   
5571   ham                                     Rofl true name      26   

      New_length  
0             82  
1             23  
2            135  
3             35  
4             43  
...          ...  
5567         111  
5568          27  
5569          27  
5570          82  
5571          14  

[5572 rows x 4 columns]

In [239]:
dataset.groupby('res').describe()

length                                                           \
       count        mean        std   min    25%    50%    75%    max   
res                                                                     
ham   4825.0   71.482487  58.440652   2.0   33.0   52.0   93.0  910.0   
spam   747.0  138.670683  28.873603  13.0  133.0  149.0  157.0  223.0   

     New_length                                                          
          count        mean        std   min   25%    50%    75%    max  
res                                                                      
ham      4825.0   46.034404  38.455996   0.0  21.0   34.0   61.0  516.0  
spam      747.0  107.124498  25.685180  12.0  97.0  112.0  125.0  159.0

In [240]:
ham_msg = dataset[dataset.res=='ham']

In [241]:
spam_msg = dataset[dataset.res=='spam']

In [242]:
print(ham_msg,spam_msg)

      res                                               feat  length  \
0     ham  Go jurong point crazy Available bugis n great ...     111   
1     ham                            Ok lar Joking wif u oni      29   
3     ham                U dun say early hor U c already say      49   
4     ham        Nah dont think goes usf lives around though      61   
6     ham     Even brother like speak treat like aids patent      77   
...   ...                                                ...     ...   
5565  ham                                            Huh lei      12   
5568  ham                        ü b going esplanade fr home      36   
5569  ham                        Pity mood Soany suggestions      57   
5570  ham  guy bitching acted like id interested buying s...     125   
5571  ham                                     Rofl true name      26   

      New_length  
0             82  
1             23  
3             35  
4             43  
6             46  
...          ...  
55

In [243]:
ham_msg_df = ham_msg.sample(n=len(spam_msg),random_state=44)

In [244]:
print(len(ham_msg_df),len(spam_msg))

747 747


In [245]:
msg_df = ham_msg_df.append(spam_msg).reset_index(drop=True)

In [246]:
msg_df

res                                               feat  length  \
0      ham  Height recycling Read twice People spend time ...     149   
1      ham  Yup song bro creative Neva test quality said c...      74   
2      ham  Feb ltgt LOVE U day Send dis ur VALUED FRNDS e...     165   
3      ham  Dont forget owns whos private property good bo...     111   
4      ham              Lol need cash nitros Hurry come crash      75   
...    ...                                                ...     ...   
1489  spam  Want explicit SEX 30 secs Ring 02073162414 Cos...      90   
1490  spam  ASKED 3MOBILE 0870 CHATLINES INCLU FREE MINS I...     158   
1491  spam  contract mobile 11 Mnths Latest Motorola Nokia...     160   
1492  spam  REMINDER O2 get 250 pounds free call credit de...     147   
1493  spam  2nd time tried 2 contact u U £750 Pound prize ...     160   

      New_length  
0            111  
1             64  
2            122  
3             70  
4             37  
...          ...  
1489          80  
1490         138  
1491         120  
1492         107  
1493         111  

[1494 rows x 4 columns]

In [247]:
msg_df['res'] = msg_df['res'].map({'ham':0,'spam':1})

In [248]:
msg_df

res                                               feat  length  \
0       0  Height recycling Read twice People spend time ...     149   
1       0  Yup song bro creative Neva test quality said c...      74   
2       0  Feb ltgt LOVE U day Send dis ur VALUED FRNDS e...     165   
3       0  Dont forget owns whos private property good bo...     111   
4       0              Lol need cash nitros Hurry come crash      75   
...   ...                                                ...     ...   
1489    1  Want explicit SEX 30 secs Ring 02073162414 Cos...      90   
1490    1  ASKED 3MOBILE 0870 CHATLINES INCLU FREE MINS I...     158   
1491    1  contract mobile 11 Mnths Latest Motorola Nokia...     160   
1492    1  REMINDER O2 get 250 pounds free call credit de...     147   
1493    1  2nd time tried 2 contact u U £750 Pound prize ...     160   

      New_length  
0            111  
1             64  
2            122  
3             70  
4             37  
...          ...  
1489          80  
1490         138  
1491         120  
1492         107  
1493         111  

[1494 rows x 4 columns]

In [249]:
X_feature = msg_df['feat'].values
Y_target = msg_df['res'].values

In [250]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_feature,Y_target)

In [251]:
#start text processing with vectorizer 
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer
from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('CountVect',CountVectorizer()),
    ('tfidf',TfidfTransformer()),
    ('Naive_bayes',BernoulliNB())
])

In [252]:
pipeline1 = Pipeline([
    ('CountVect',CountVectorizer()),
    ('tfidf',TfidfTransformer()),
    ('KNN',KNeighborsClassifier())
])

In [253]:
pipeline2 = Pipeline([
    ('CountVect',CountVectorizer()),
    ('tfidf',TfidfTransformer()),
    ('DecisionTree',DecisionTreeClassifier())
])

In [254]:
#use bag of words by applying the function and fit the data into it

In [255]:
pipeline.fit(X_train,Y_train)

Pipeline(steps=[('CountVect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('Naive_bayes', BernoulliNB())])

In [256]:
#print length of bag of words stored in the vocabulary_ attribute

In [257]:
#apply tfidf transformer and fit the bag of words into it (transformed version)


In [258]:
#print shape of the tfidf 


In [259]:
#choose naive Bayes model to detect the spam and fit the tfidf data into it
Y_predict = pipeline.predict(X_test)

In [260]:
#check model for the predicted and expected value say for message#2 and message#5


In [261]:
#Evaluate the accuracy of your model
from sklearn.metrics import accuracy_score,average_precision_score,confusion_matrix,f1_score,recall_score
print("accuracy_score",accuracy_score(Y_test,Y_predict))
print("average_precision_score",average_precision_score(Y_test,Y_predict))
print("confusion_matrix\n",confusion_matrix(Y_test,Y_predict))
print("\nrecall_score",recall_score(Y_test,Y_predict))
print("\nf1_score",f1_score(Y_test,Y_predict))

accuracy_score 0.946524064171123
average_precision_score 0.939104994792317
confusion_matrix
 [[194   1]
 [ 19 160]]

recall_score 0.8938547486033519

f1_score 0.9411764705882352


In [262]:
parameters = {
    'tfidf__use_idf':(True,False),
             }

In [263]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(pipeline1,parameters,n_jobs=-1,verbose=1,scoring='f1')

In [264]:
grid_search1 = GridSearchCV(pipeline2,parameters,n_jobs=-1,verbose=1,scoring='f1')

In [265]:
grid_search.fit(X_train,Y_train)

Fitting 5 folds for each of 2 candidates, totalling 10 fits


GridSearchCV(estimator=Pipeline(steps=[('CountVect', CountVectorizer()),
                                       ('tfidf', TfidfTransformer()),
                                       ('KNN', KNeighborsClassifier())]),
             n_jobs=-1, param_grid={'tfidf__use_idf': (True, False)},
             scoring='f1', verbose=1)

In [266]:
Y_predict = grid_search.predict(X_test)

In [267]:
#Evaluate the accuracy of your model
from sklearn.metrics import accuracy_score,average_precision_score,confusion_matrix,f1_score,recall_score
print("accuracy_score",accuracy_score(Y_test,Y_predict))
print("average_precision_score",average_precision_score(Y_test,Y_predict))
print("confusion_matrix\n",confusion_matrix(Y_test,Y_predict))
print("\nrecall_score",recall_score(Y_test,Y_predict))
print("\nf1_score",f1_score(Y_test,Y_predict))

accuracy_score 0.9117647058823529
average_precision_score 0.8656947718728856
confusion_matrix
 [[177  18]
 [ 15 164]]

recall_score 0.9162011173184358

f1_score 0.9085872576177285


In [268]:
grid_search1.fit(X_train,Y_train)

Fitting 5 folds for each of 2 candidates, totalling 10 fits


GridSearchCV(estimator=Pipeline(steps=[('CountVect', CountVectorizer()),
                                       ('tfidf', TfidfTransformer()),
                                       ('DecisionTree',
                                        DecisionTreeClassifier())]),
             n_jobs=-1, param_grid={'tfidf__use_idf': (True, False)},
             scoring='f1', verbose=1)

In [269]:
Y_predict = grid_search.predict(X_test)

In [270]:
#Evaluate the accuracy of your model
from sklearn.metrics import accuracy_score,average_precision_score,confusion_matrix,f1_score,recall_score
print("accuracy_score",accuracy_score(Y_test,Y_predict))
print("average_precision_score",average_precision_score(Y_test,Y_predict))
print("confusion_matrix\n",confusion_matrix(Y_test,Y_predict))
print("\nrecall_score",recall_score(Y_test,Y_predict))
print("\nf1_score",f1_score(Y_test,Y_predict))

accuracy_score 0.9117647058823529
average_precision_score 0.8656947718728856
confusion_matrix
 [[177  18]
 [ 15 164]]

recall_score 0.9162011173184358

f1_score 0.9085872576177285
